# -*- coding: utf-8 -*-
"""API실습.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1voPOHqzIWnDmCHxfSzjacBWNVwLOQrLI

## 영화 API
"""

import pandas as pd
import requests
from google.colab import userdata
import xml.etree.ElementTree as ET

# request
url = 'http://api.kcisa.kr/openapi/service/rest/meta5/getKFCC0502'

params = {
    ('serviceKey', userdata.get('boxoffice_api_key'))
    }

response = requests.get(url, params)

# 확인용
# print(response.text)

# XML parsing
root = ET.fromstring(response.text)
data = []

for item in root.findall('.//item'):
    item_data = {}
    for child in item:
        item_data[child.tag] = child.text
    data.append(item_data)

df = pd.DataFrame(data)
df.head()



df.head(10)

"""## 날씨 API"""

import pandas as pd
import requests
from google.colab import userdata
import xml.etree.ElementTree as ET

# request
url = 'http://apis.data.go.kr/1360000/WthrWrnInfoService/getWthrWrnList'

params = {
    ('ServiceKey', userdata.get('weather_api_decoding')),
    ('pageNo', '1'),
    ('numOfRows', '30'),
    ('fromTmFc', '20250113'),
    ('toTmFc', '20250118')
    }

response = requests.get(url, params)

# 확인용
#print(response.text)

# XML parsing
root = ET.fromstring(response.text)
data = []

for item in root.findall('.//item'):
    item_data = {}
    for child in item:
        item_data[child.tag] = child.text
    data.append(item_data)

df = pd.DataFrame(data)
df.head()

